# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(704, 871)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LstSrcImg = QtWidgets.QListWidget(self.centralwidget)
        self.LstSrcImg.setGeometry(QtCore.QRect(9, 119, 256, 411))
        self.LstSrcImg.setObjectName("LstSrcImg")
        self.LblSrcImg = QtWidgets.QLabel(self.centralwidget)
        self.LblSrcImg.setGeometry(QtCore.QRect(280, 120, 200, 200))
        self.LblSrcImg.setFrameShape(QtWidgets.QFrame.Box)
        self.LblSrcImg.setText("")
        self.LblSrcImg.setObjectName("LblSrcImg")
        self.LblDstImg = QtWidgets.QLabel(self.centralwidget)
        self.LblDstImg.setGeometry(QtCore.QRect(490, 120, 200, 200))
        self.LblDstImg.setFrameShape(QtWidgets.QFrame.Box)
        self.LblDstImg.setText("")
        self.LblDstImg.setObjectName("LblDstImg")
        self.LstNNImg = QtWidgets.QListWidget(self.centralwidget)
        self.LstNNImg.setGeometry(QtCore.QRect(10, 540, 256, 201))
        self.LstNNImg.setObjectName("LstNNImg")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 329, 201, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.VBoxSrc = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.VBoxSrc.setContentsMargins(0, 0, 0, 0)
        self.VBoxSrc.setObjectName("VBoxSrc")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(490, 330, 201, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.VBoxDst = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.VBoxDst.setContentsMargins(0, 0, 0, 0)
        self.VBoxDst.setObjectName("VBoxDst")
        self.LblNN = QtWidgets.QLabel(self.centralwidget)
        self.LblNN.setGeometry(QtCore.QRect(280, 540, 200, 200))
        self.LblNN.setFrameShape(QtWidgets.QFrame.Box)
        self.LblNN.setText("")
        self.LblNN.setObjectName("LblNN")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(490, 540, 201, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.VBoxNN = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.VBoxNN.setContentsMargins(0, 0, 0, 0)
        self.VBoxNN.setObjectName("VBoxNN")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 750, 251, 72))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(270, 750, 421, 72))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LblDirSrcImg = QtWidgets.QLabel(self.layoutWidget1)
        self.LblDirSrcImg.setText("")
        self.LblDirSrcImg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LblDirSrcImg.setObjectName("LblDirSrcImg")
        self.verticalLayout_2.addWidget(self.LblDirSrcImg)
        self.LblDirResFilter = QtWidgets.QLabel(self.layoutWidget1)
        self.LblDirResFilter.setText("")
        self.LblDirResFilter.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LblDirResFilter.setObjectName("LblDirResFilter")
        self.verticalLayout_2.addWidget(self.LblDirResFilter)
        self.LblDirResNN = QtWidgets.QLabel(self.layoutWidget1)
        self.LblDirResNN.setText("")
        self.LblDirResNN.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LblDirResNN.setObjectName("LblDirResNN")
        self.verticalLayout_2.addWidget(self.LblDirResNN)
        self.LblDbNN = QtWidgets.QLabel(self.layoutWidget1)
        self.LblDbNN.setText("")
        self.LblDbNN.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LblDbNN.setObjectName("LblDbNN")
        self.verticalLayout_2.addWidget(self.LblDbNN)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 0, 31, 16))
        self.label_5.setObjectName("label_5")
        self.SliderGlobal = QtWidgets.QSlider(self.centralwidget)
        self.SliderGlobal.setGeometry(QtCore.QRect(20, 30, 160, 22))
        self.SliderGlobal.setMaximum(255)
        self.SliderGlobal.setOrientation(QtCore.Qt.Horizontal)
        self.SliderGlobal.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SliderGlobal.setObjectName("SliderGlobal")
        self.SpinGlobal = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinGlobal.setGeometry(QtCore.QRect(180, 30, 42, 22))
        self.SpinGlobal.setMaximum(255)
        self.SpinGlobal.setObjectName("SpinGlobal")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 60, 681, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.ActImgs = QtWidgets.QAction(MainWindow)
        self.ActImgs.setObjectName("ActImgs")
        self.ActThreshGlobal = QtWidgets.QAction(MainWindow)
        self.ActThreshGlobal.setObjectName("ActThreshGlobal")
        self.ActRunNN = QtWidgets.QAction(MainWindow)
        self.ActRunNN.setObjectName("ActRunNN")
        self.ActTrainImg = QtWidgets.QAction(MainWindow)
        self.ActTrainImg.setObjectName("ActTrainImg")
        self.ActSrcImg = QtWidgets.QAction(MainWindow)
        self.ActSrcImg.setObjectName("ActSrcImg")
        self.ActAugImg = QtWidgets.QAction(MainWindow)
        self.ActAugImg.setObjectName("ActAugImg")
        self.ActThreshGaussian = QtWidgets.QAction(MainWindow)
        self.ActThreshGaussian.setObjectName("ActThreshGaussian")
        self.ActThreshOtsu = QtWidgets.QAction(MainWindow)
        self.ActThreshOtsu.setObjectName("ActThreshOtsu")
        self.ActThreshMean = QtWidgets.QAction(MainWindow)
        self.ActThreshMean.setObjectName("ActThreshMean")
        self.ActTestImg = QtWidgets.QAction(MainWindow)
        self.ActTestImg.setObjectName("ActTestImg")
        self.ActDbNN = QtWidgets.QAction(MainWindow)
        self.ActDbNN.setObjectName("ActDbNN")
        self.ActThreshGaussianAndOtsu = QtWidgets.QAction(MainWindow)
        self.ActThreshGaussianAndOtsu.setObjectName("ActThreshGaussianAndOtsu")
        self.ActJPG_PNG = QtWidgets.QAction(MainWindow)
        self.ActJPG_PNG.setObjectName("ActJPG_PNG")
        self.menu.addAction(self.ActImgs)
        self.menu.addAction(self.ActJPG_PNG)
        self.menu_2.addAction(self.ActThreshGlobal)
        self.menu_2.addAction(self.ActThreshGaussian)
        self.menu_2.addAction(self.ActThreshOtsu)
        self.menu_2.addAction(self.ActThreshMean)
        self.menu_2.addAction(self.ActThreshGaussianAndOtsu)
        self.menu_2.addSeparator()
        self.menu_3.addAction(self.ActTestImg)
        self.menu_3.addAction(self.ActDbNN)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.ActSrcImg)
        self.menu_3.addAction(self.ActTrainImg)
        self.menu_3.addAction(self.ActAugImg)
        self.menu_3.addAction(self.ActRunNN)
        self.menu_3.addSeparator()
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Директория с исходными изображениями:"))
        self.label_2.setText(_translate("MainWindow", "Директория результата применения фильтра:"))
        self.label_3.setText(_translate("MainWindow", "Директория резултата нейронной сети:"))
        self.label_4.setText(_translate("MainWindow", "База данных весов нейронной сети:"))
        self.label_5.setText(_translate("MainWindow", "Global"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Операции"))
        self.menu_3.setTitle(_translate("MainWindow", "Нейронная сеть"))
        self.ActImgs.setText(_translate("MainWindow", "Директория изображений"))
        self.ActThreshGlobal.setText(_translate("MainWindow", "Метод Global"))
        self.ActRunNN.setText(_translate("MainWindow", "Запустить обучение нейронной сети"))
        self.ActTrainImg.setText(_translate("MainWindow", "Директория с масками"))
        self.ActSrcImg.setText(_translate("MainWindow", "Директория с исходными данными"))
        self.ActAugImg.setText(_translate("MainWindow", "Директория тренировочных данных"))
        self.ActThreshGaussian.setText(_translate("MainWindow", "Метод Gaussian"))
        self.ActThreshOtsu.setText(_translate("MainWindow", "Метод Otsu"))
        self.ActThreshMean.setText(_translate("MainWindow", "Метод Mean"))
        self.ActTestImg.setText(_translate("MainWindow", "Данные для тестирования"))
        self.ActDbNN.setText(_translate("MainWindow", "База данных весов"))
        self.ActThreshGaussianAndOtsu.setText(_translate("MainWindow", "Метод Gaussian и Otsu"))
        self.ActJPG_PNG.setText(_translate("MainWindow", "Конвертировать из JPG в PNG"))
