# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 690)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Tab.setObjectName("Tab")
        self.TabTools = QtWidgets.QWidget()
        self.TabTools.setObjectName("TabTools")
        self.LstSrcImg = QtWidgets.QListWidget(self.TabTools)
        self.LstSrcImg.setGeometry(QtCore.QRect(10, 180, 256, 411))
        self.LstSrcImg.setObjectName("LstSrcImg")
        self.LblDstImg = QtWidgets.QLabel(self.TabTools)
        self.LblDstImg.setGeometry(QtCore.QRect(491, 181, 200, 200))
        self.LblDstImg.setFrameShape(QtWidgets.QFrame.Box)
        self.LblDstImg.setText("")
        self.LblDstImg.setObjectName("LblDstImg")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.TabTools)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(281, 390, 201, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.VBoxSrcFilter = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.VBoxSrcFilter.setContentsMargins(0, 0, 0, 0)
        self.VBoxSrcFilter.setObjectName("VBoxSrcFilter")
        self.LblSrcImg = QtWidgets.QLabel(self.TabTools)
        self.LblSrcImg.setGeometry(QtCore.QRect(281, 181, 200, 200))
        self.LblSrcImg.setFrameShape(QtWidgets.QFrame.Box)
        self.LblSrcImg.setText("")
        self.LblSrcImg.setObjectName("LblSrcImg")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.TabTools)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(491, 391, 201, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.VBoxDstFilter = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.VBoxDstFilter.setContentsMargins(0, 0, 0, 0)
        self.VBoxDstFilter.setObjectName("VBoxDstFilter")
        self.label_5 = QtWidgets.QLabel(self.TabTools)
        self.label_5.setGeometry(QtCore.QRect(550, 120, 31, 16))
        self.label_5.setObjectName("label_5")
        self.SliderGlobal = QtWidgets.QSlider(self.TabTools)
        self.SliderGlobal.setGeometry(QtCore.QRect(490, 150, 160, 22))
        self.SliderGlobal.setMaximum(255)
        self.SliderGlobal.setOrientation(QtCore.Qt.Horizontal)
        self.SliderGlobal.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.SliderGlobal.setObjectName("SliderGlobal")
        self.SpinGlobal = QtWidgets.QSpinBox(self.TabTools)
        self.SpinGlobal.setGeometry(QtCore.QRect(650, 150, 42, 22))
        self.SpinGlobal.setMaximum(255)
        self.SpinGlobal.setObjectName("SpinGlobal")
        self.LineSrcImg = QtWidgets.QLineEdit(self.TabTools)
        self.LineSrcImg.setGeometry(QtCore.QRect(20, 30, 671, 20))
        self.LineSrcImg.setObjectName("LineSrcImg")
        self.BtnSrcImg = QtWidgets.QPushButton(self.TabTools)
        self.BtnSrcImg.setGeometry(QtCore.QRect(700, 30, 75, 23))
        self.BtnSrcImg.setObjectName("BtnSrcImg")
        self.label_13 = QtWidgets.QLabel(self.TabTools)
        self.label_13.setGeometry(QtCore.QRect(20, 10, 671, 16))
        self.label_13.setObjectName("label_13")
        self.BtnJpgToPng = QtWidgets.QPushButton(self.TabTools)
        self.BtnJpgToPng.setGeometry(QtCore.QRect(700, 80, 75, 23))
        self.BtnJpgToPng.setObjectName("BtnJpgToPng")
        self.label_16 = QtWidgets.QLabel(self.TabTools)
        self.label_16.setGeometry(QtCore.QRect(20, 60, 671, 16))
        self.label_16.setObjectName("label_16")
        self.LineJpgToPng = QtWidgets.QLineEdit(self.TabTools)
        self.LineJpgToPng.setGeometry(QtCore.QRect(20, 80, 671, 20))
        self.LineJpgToPng.setObjectName("LineJpgToPng")
        self.BtnApplyFilterAll = QtWidgets.QPushButton(self.TabTools)
        self.BtnApplyFilterAll.setGeometry(QtCore.QRect(700, 180, 91, 23))
        self.BtnApplyFilterAll.setObjectName("BtnApplyFilterAll")
        self.BtnConvertJpgToPng = QtWidgets.QPushButton(self.TabTools)
        self.BtnConvertJpgToPng.setGeometry(QtCore.QRect(700, 110, 101, 23))
        self.BtnConvertJpgToPng.setObjectName("BtnConvertJpgToPng")
        self.LineSaveFilterImg = QtWidgets.QLineEdit(self.TabTools)
        self.LineSaveFilterImg.setGeometry(QtCore.QRect(20, 150, 341, 20))
        self.LineSaveFilterImg.setObjectName("LineSaveFilterImg")
        self.BtnSaveFilterImg = QtWidgets.QPushButton(self.TabTools)
        self.BtnSaveFilterImg.setGeometry(QtCore.QRect(370, 150, 91, 23))
        self.BtnSaveFilterImg.setObjectName("BtnSaveFilterImg")
        self.BtnApplyFilter = QtWidgets.QPushButton(self.TabTools)
        self.BtnApplyFilter.setGeometry(QtCore.QRect(700, 150, 91, 23))
        self.BtnApplyFilter.setObjectName("BtnApplyFilter")
        self.label = QtWidgets.QLabel(self.TabTools)
        self.label.setGeometry(QtCore.QRect(20, 130, 341, 16))
        self.label.setObjectName("label")
        self.Tab.addTab(self.TabTools, "")
        self.TabTrainNN = QtWidgets.QWidget()
        self.TabTrainNN.setObjectName("TabTrainNN")
        self.SpinEpochs = QtWidgets.QSpinBox(self.TabTrainNN)
        self.SpinEpochs.setGeometry(QtCore.QRect(210, 40, 61, 22))
        self.SpinEpochs.setMaximum(1000)
        self.SpinEpochs.setProperty("value", 1)
        self.SpinEpochs.setObjectName("SpinEpochs")
        self.label_14 = QtWidgets.QLabel(self.TabTrainNN)
        self.label_14.setGeometry(QtCore.QRect(210, 20, 101, 16))
        self.label_14.setObjectName("label_14")
        self.SpinStepEpochs = QtWidgets.QSpinBox(self.TabTrainNN)
        self.SpinStepEpochs.setGeometry(QtCore.QRect(30, 40, 71, 22))
        self.SpinStepEpochs.setMaximum(5000)
        self.SpinStepEpochs.setProperty("value", 300)
        self.SpinStepEpochs.setObjectName("SpinStepEpochs")
        self.label_15 = QtWidgets.QLabel(self.TabTrainNN)
        self.label_15.setGeometry(QtCore.QRect(30, 20, 121, 16))
        self.label_15.setObjectName("label_15")
        self.LineSrcData = QtWidgets.QLineEdit(self.TabTrainNN)
        self.LineSrcData.setGeometry(QtCore.QRect(30, 140, 321, 20))
        self.LineSrcData.setObjectName("LineSrcData")
        self.LineMasksData = QtWidgets.QLineEdit(self.TabTrainNN)
        self.LineMasksData.setGeometry(QtCore.QRect(30, 180, 321, 20))
        self.LineMasksData.setObjectName("LineMasksData")
        self.LineAugData = QtWidgets.QLineEdit(self.TabTrainNN)
        self.LineAugData.setGeometry(QtCore.QRect(30, 220, 321, 20))
        self.LineAugData.setObjectName("LineAugData")
        self.label_10 = QtWidgets.QLabel(self.TabTrainNN)
        self.label_10.setGeometry(QtCore.QRect(30, 120, 651, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.TabTrainNN)
        self.label_11.setGeometry(QtCore.QRect(30, 160, 651, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.TabTrainNN)
        self.label_12.setGeometry(QtCore.QRect(30, 200, 651, 16))
        self.label_12.setObjectName("label_12")
        self.BtnTrainNN = QtWidgets.QPushButton(self.TabTrainNN)
        self.BtnTrainNN.setGeometry(QtCore.QRect(690, 300, 81, 23))
        self.BtnTrainNN.setObjectName("BtnTrainNN")
        self.LineDbSaveWeight = QtWidgets.QLineEdit(self.TabTrainNN)
        self.LineDbSaveWeight.setGeometry(QtCore.QRect(30, 260, 651, 20))
        self.LineDbSaveWeight.setText("")
        self.LineDbSaveWeight.setObjectName("LineDbSaveWeight")
        self.label_17 = QtWidgets.QLabel(self.TabTrainNN)
        self.label_17.setGeometry(QtCore.QRect(30, 240, 651, 16))
        self.label_17.setObjectName("label_17")
        self.BtnDbSaveWeight = QtWidgets.QPushButton(self.TabTrainNN)
        self.BtnDbSaveWeight.setGeometry(QtCore.QRect(690, 260, 75, 23))
        self.BtnDbSaveWeight.setObjectName("BtnDbSaveWeight")
        self.LineTrainData = QtWidgets.QLineEdit(self.TabTrainNN)
        self.LineTrainData.setGeometry(QtCore.QRect(30, 100, 651, 20))
        self.LineTrainData.setText("")
        self.LineTrainData.setObjectName("LineTrainData")
        self.label_21 = QtWidgets.QLabel(self.TabTrainNN)
        self.label_21.setGeometry(QtCore.QRect(30, 80, 651, 16))
        self.label_21.setObjectName("label_21")
        self.BtnTrainData = QtWidgets.QPushButton(self.TabTrainNN)
        self.BtnTrainData.setGeometry(QtCore.QRect(690, 100, 75, 23))
        self.BtnTrainData.setObjectName("BtnTrainData")
        self.Tab.addTab(self.TabTrainNN, "")
        self.TabTestNN = QtWidgets.QWidget()
        self.TabTestNN.setObjectName("TabTestNN")
        self.LblNN = QtWidgets.QLabel(self.TabTestNN)
        self.LblNN.setGeometry(QtCore.QRect(280, 230, 200, 200))
        self.LblNN.setFrameShape(QtWidgets.QFrame.Box)
        self.LblNN.setText("")
        self.LblNN.setObjectName("LblNN")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.TabTestNN)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(490, 230, 201, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.VBoxTestNN = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.VBoxTestNN.setContentsMargins(0, 0, 0, 0)
        self.VBoxTestNN.setObjectName("VBoxTestNN")
        self.LstNNImg = QtWidgets.QListWidget(self.TabTestNN)
        self.LstNNImg.setGeometry(QtCore.QRect(10, 230, 256, 201))
        self.LstNNImg.setObjectName("LstNNImg")
        self.LineTestData = QtWidgets.QLineEdit(self.TabTestNN)
        self.LineTestData.setGeometry(QtCore.QRect(20, 50, 671, 20))
        self.LineTestData.setObjectName("LineTestData")
        self.LineDbOpenWeights = QtWidgets.QLineEdit(self.TabTestNN)
        self.LineDbOpenWeights.setGeometry(QtCore.QRect(20, 130, 671, 20))
        self.LineDbOpenWeights.setObjectName("LineDbOpenWeights")
        self.BtnTestData = QtWidgets.QPushButton(self.TabTestNN)
        self.BtnTestData.setGeometry(QtCore.QRect(700, 50, 75, 23))
        self.BtnTestData.setObjectName("BtnTestData")
        self.BtnDbOpenWeights = QtWidgets.QPushButton(self.TabTestNN)
        self.BtnDbOpenWeights.setGeometry(QtCore.QRect(700, 130, 75, 23))
        self.BtnDbOpenWeights.setObjectName("BtnDbOpenWeights")
        self.BtnTestNN = QtWidgets.QPushButton(self.TabTestNN)
        self.BtnTestNN.setGeometry(QtCore.QRect(700, 170, 75, 23))
        self.BtnTestNN.setObjectName("BtnTestNN")
        self.label_18 = QtWidgets.QLabel(self.TabTestNN)
        self.label_18.setGeometry(QtCore.QRect(20, 30, 671, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.TabTestNN)
        self.label_19.setGeometry(QtCore.QRect(20, 110, 671, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.TabTestNN)
        self.label_20.setGeometry(QtCore.QRect(20, 70, 671, 16))
        self.label_20.setObjectName("label_20")
        self.BtnTestResult = QtWidgets.QPushButton(self.TabTestNN)
        self.BtnTestResult.setGeometry(QtCore.QRect(700, 90, 75, 23))
        self.BtnTestResult.setObjectName("BtnTestResult")
        self.LineTestResult = QtWidgets.QLineEdit(self.TabTestNN)
        self.LineTestResult.setGeometry(QtCore.QRect(20, 90, 671, 20))
        self.LineTestResult.setObjectName("LineTestResult")
        self.Tab.addTab(self.TabTestNN, "")
        self.gridLayout.addWidget(self.Tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.ActImgs = QtWidgets.QAction(MainWindow)
        self.ActImgs.setObjectName("ActImgs")
        self.ActThreshGlobal = QtWidgets.QAction(MainWindow)
        self.ActThreshGlobal.setObjectName("ActThreshGlobal")
        self.ActRunTrainNN = QtWidgets.QAction(MainWindow)
        self.ActRunTrainNN.setObjectName("ActRunTrainNN")
        self.ActTrainData = QtWidgets.QAction(MainWindow)
        self.ActTrainData.setObjectName("ActTrainData")
        self.ActThreshGaussian = QtWidgets.QAction(MainWindow)
        self.ActThreshGaussian.setObjectName("ActThreshGaussian")
        self.ActThreshOtsu = QtWidgets.QAction(MainWindow)
        self.ActThreshOtsu.setObjectName("ActThreshOtsu")
        self.ActThreshMean = QtWidgets.QAction(MainWindow)
        self.ActThreshMean.setObjectName("ActThreshMean")
        self.ActTestData = QtWidgets.QAction(MainWindow)
        self.ActTestData.setObjectName("ActTestData")
        self.ActDbWeights = QtWidgets.QAction(MainWindow)
        self.ActDbWeights.setObjectName("ActDbWeights")
        self.ActThreshGaussianAndOtsu = QtWidgets.QAction(MainWindow)
        self.ActThreshGaussianAndOtsu.setObjectName("ActThreshGaussianAndOtsu")
        self.ActJPG_PNG = QtWidgets.QAction(MainWindow)
        self.ActJPG_PNG.setObjectName("ActJPG_PNG")
        self.ActRunTestNN = QtWidgets.QAction(MainWindow)
        self.ActRunTestNN.setObjectName("ActRunTestNN")
        self.ActTestResult = QtWidgets.QAction(MainWindow)
        self.ActTestResult.setObjectName("ActTestResult")
        self.ActSaveTrainData = QtWidgets.QAction(MainWindow)
        self.ActSaveTrainData.setObjectName("ActSaveTrainData")
        self.menu.addAction(self.ActImgs)
        self.menu.addAction(self.ActJPG_PNG)
        self.menu_2.addAction(self.ActThreshGlobal)
        self.menu_2.addAction(self.ActThreshGaussian)
        self.menu_2.addAction(self.ActThreshOtsu)
        self.menu_2.addAction(self.ActThreshMean)
        self.menu_2.addAction(self.ActThreshGaussianAndOtsu)
        self.menu_2.addSeparator()
        self.menu_3.addAction(self.ActTestData)
        self.menu_3.addAction(self.ActTestResult)
        self.menu_3.addAction(self.ActDbWeights)
        self.menu_3.addAction(self.ActRunTestNN)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.ActTrainData)
        self.menu_3.addAction(self.ActSaveTrainData)
        self.menu_3.addAction(self.ActRunTrainNN)
        self.menu_3.addSeparator()
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.Tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Global"))
        self.BtnSrcImg.setText(_translate("MainWindow", "Обзор"))
        self.label_13.setText(_translate("MainWindow", "Директория с изображениями"))
        self.BtnJpgToPng.setText(_translate("MainWindow", "Обзор"))
        self.label_16.setText(_translate("MainWindow", "Директория сохранения результата конвертации изображений из JPG в PNG"))
        self.BtnApplyFilterAll.setText(_translate("MainWindow", "Прим.для всех"))
        self.BtnConvertJpgToPng.setText(_translate("MainWindow", "Конвертировать"))
        self.BtnSaveFilterImg.setText(_translate("MainWindow", "Обзор"))
        self.BtnApplyFilter.setText(_translate("MainWindow", "Применить"))
        self.label.setText(_translate("MainWindow", "Директория сохранение результата выбранного фильтра"))
        self.Tab.setTabText(self.Tab.indexOf(self.TabTools), _translate("MainWindow", "Инструменты"))
        self.label_14.setText(_translate("MainWindow", "Колличество эпох"))
        self.label_15.setText(_translate("MainWindow", "Шаг выборки данных"))
        self.LineSrcData.setText(_translate("MainWindow", "images"))
        self.LineMasksData.setText(_translate("MainWindow", "masks"))
        self.LineAugData.setText(_translate("MainWindow", "aug"))
        self.label_10.setText(_translate("MainWindow", "Относительный путь к директории исходных изображений"))
        self.label_11.setText(_translate("MainWindow", "Относительный путь к директории масок"))
        self.label_12.setText(_translate("MainWindow", "Относительноый путь к директории тренировочных данных"))
        self.BtnTrainNN.setText(_translate("MainWindow", "Запуск"))
        self.label_17.setText(_translate("MainWindow", "Сохранение базы данных весов нейронной сети"))
        self.BtnDbSaveWeight.setText(_translate("MainWindow", "Обзор"))
        self.label_21.setText(_translate("MainWindow", "Директория тренировочных данных"))
        self.BtnTrainData.setText(_translate("MainWindow", "Обзор"))
        self.Tab.setTabText(self.Tab.indexOf(self.TabTrainNN), _translate("MainWindow", "Обучение нейронной сети"))
        self.BtnTestData.setText(_translate("MainWindow", "Обзор"))
        self.BtnDbOpenWeights.setText(_translate("MainWindow", "Обзор"))
        self.BtnTestNN.setText(_translate("MainWindow", "Запуск"))
        self.label_18.setText(_translate("MainWindow", "Дериктория тестируемых данных"))
        self.label_19.setText(_translate("MainWindow", "База данных весов нейронной сети"))
        self.label_20.setText(_translate("MainWindow", "Дериктория сохранения результата"))
        self.BtnTestResult.setText(_translate("MainWindow", "Обзор"))
        self.Tab.setTabText(self.Tab.indexOf(self.TabTestNN), _translate("MainWindow", "Тестирование нейронной сети"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Операции"))
        self.menu_3.setTitle(_translate("MainWindow", "Нейронная сеть"))
        self.ActImgs.setText(_translate("MainWindow", "Директория изображений"))
        self.ActThreshGlobal.setText(_translate("MainWindow", "Метод Global"))
        self.ActRunTrainNN.setText(_translate("MainWindow", "Запустить обучение нейронной сети"))
        self.ActTrainData.setText(_translate("MainWindow", "Директория тренировочных данных"))
        self.ActThreshGaussian.setText(_translate("MainWindow", "Метод Gaussian"))
        self.ActThreshOtsu.setText(_translate("MainWindow", "Метод Otsu"))
        self.ActThreshMean.setText(_translate("MainWindow", "Метод Mean"))
        self.ActTestData.setText(_translate("MainWindow", "Директория тестируемых данных"))
        self.ActDbWeights.setText(_translate("MainWindow", "База данных весов нейронной сети"))
        self.ActThreshGaussianAndOtsu.setText(_translate("MainWindow", "Метод Gaussian и Otsu"))
        self.ActJPG_PNG.setText(_translate("MainWindow", "Конвертировать из JPG в PNG"))
        self.ActRunTestNN.setText(_translate("MainWindow", "Запустить тестирование нейронной сети"))
        self.ActTestResult.setText(_translate("MainWindow", "Директория сохранения результата"))
        self.ActSaveTrainData.setText(_translate("MainWindow", "Директория сохранения базы данных весов нейронной сети"))
